### ISSUE TITLE
遇到的一些绘图以及精度问题~希望大佬看一下呀

### ISSUE THREAD

**Issue by sky-fly97** [edwardning/PyTorch-YOLOv3-ModelArts#1]
大佬你好，我遇到了三个问题...
1、模型判分时间，第一次训练了10+10个epoch，提交后两个小时才出，成绩0.03...，然后改了一下推理代码中score阈值为0.0001，三个小时后提示判分失败。
2、在线部署的框问题，在线预测的时候基本上所有的图片输出的框都是带有负坐标，框完全把图片覆盖了，并且看不到边界...不知道这种情况是为什么呀...
3、模型精度问题，目前训练50+epoch， 日志val只有10左右，目前刚刚尝试提交这个新模型，应该分数同样比较低，而在线预测的框由于负值坐标无法判别。

打扰到大佬了，不知道存在哪些问题，谢谢大佬！

**Comment by sky-fly97** [comment]
![_L3CA}CMKD~B3T@PUT6~RVQ](https://user-images.githubusercontent.com/55578436/82225805-3dba1b00-9958-11ea-989c-cc91b178f063.png)
![AGIQOD1OF%U2GNZZB{}AB5O](https://user-images.githubusercontent.com/55578436/82225825-43176580-9958-11ea-988a-787c8ecc9ff5.png)
![1~{Z%5YLV8RU@RL$@$ 10XL](https://user-images.githubusercontent.com/55578436/82225831-47dc1980-9958-11ea-901f-904dcc7ea2ca.png)
![Y}N0))R``_X9KQU07}ZA{BW](https://user-images.githubusercontent.com/55578436/82225842-4ad70a00-9958-11ea-907f-61fb7d143880.png)
![J9$B0@`LFF~EL72Y4Q@JJ}6](https://user-images.githubusercontent.com/55578436/82225878-54607200-9958-11ea-84fe-d73018e4c29e.png)

**Comment by sky-fly97** [comment]
emmm遇到一个很奇怪的事情，晚上训练提交的50ep跟70ep的时间都在评分1小时内，50ep的评分0.018，70ep评分0.18，我惊了.....这啥逻辑呀

**Comment by sky-fly97** [comment]
为此我又把70ep的模型在线部署了一下，负坐标没有了，真的邪门啊啊啊啊啊啊啊啊啊啊啊啊啊，心态崩了。。。

不过同样一个问题就是在线预测的时候框的x y是反的，不知道评分的时候会不会按正常的xyxy来判..

**Comment by sky-fly97** [comment]
不过确实到了后面不管是loss还是val的map都好难降了呀，loss稳定5左右，val一直在10左右震荡

**Comment by selous123** [comment]
> 为此我又把70ep的模型在线部署了一下，负坐标没有了，真的邪门啊啊啊啊啊啊啊啊啊啊啊啊啊，心态崩了。。。
> 
> 不过同样一个问题就是在线预测的时候框的x y是反的，不知道评分的时候会不会按正常的xyxy来判..

在线预测显示需要按照(y_min,x_min.y_max,x_max)显示，而评测是按照(x_min,y_min,x_max,y_max)。所以你在线预测显示反的，提交就没有问题。

**Comment by selous123** [comment]
1. 我也尝试了这个代码，不管是加载预训练参数darknet还是直接训练，都会出现recall=0,precision=0, 而且验证集上精度很低的问题。
2. 我也尝试了 eriklindernoren/PyTorch-YOLOv3 也一样有这个问题。
想水个比赛好难呀

**Comment by edwardning** [comment]
> 大佬你好，我遇到了三个问题...
> 1、模型判分时间，第一次训练了10+10个epoch，提交后两个小时才出，成绩0.03...，然后改了一下推理代码中score阈值为0.0001，三个小时后提示判分失败。
> 2、在线部署的框问题，在线预测的时候基本上所有的图片输出的框都是带有负坐标，框完全把图片覆盖了，并且看不到边界...不知道这种情况是为什么呀...
> 3、模型精度问题，目前训练50+epoch， 日志val只有10左右，目前刚刚尝试提交这个新模型，应该分数同样比较低，而在线预测的框由于负值坐标无法判别。
> 
> 打扰到大佬了，不知道存在哪些问题，谢谢大佬！

1. 官方baseline判分大概会两个小时，我这个多方测试不到一小时。你用的是我这个嘛？
2.在线预测和判分坐标格式不一样，代码里是按判分输出的，所以不影响判分。
3.只训练头部（freeze_body=2），训练5epoch就会17左右。你50epoch才10，肯定是改了哪里的训练参数了吧？如果一开始就从头训练（freeze_body=0）的话，得分是会低很多的。

**Comment by edwardning** [comment]
> 1. 我也尝试了这个代码，不管是加载预训练参数darknet还是直接训练，都会出现recall=0,precision=0, 而且验证集上精度很低的问题。
> 2. 我也尝试了 eriklindernoren/PyTorch-YOLOv3 也一样有这个问题。
>    想水个比赛好难呀

1. 建议加载yolov3.weights训练。代码开始默认加载backbone（应该是你试的版本），现在已经更新了。新版本训练5个epoch就会到17.
2. 同1，建议加载yolov3.weights，然后冻结出三个输出层之外所有的层（freeze_body=2），稍加训练就会稳定。之后再慢慢调参。

**Comment by edwardning** [comment]
> 不过确实到了后面不管是loss还是val的map都好难降了呀，loss稳定5左右，val一直在10左右震荡

继续降低学习率试试

**Comment by sky-fly97** [comment]
> > 不过确实到了后面不管是loss还是val的map都好难降了呀，loss稳定5左右，val一直在10左右震荡
> 
> 继续降低学习率试试

感谢大佬，我是从backbone开始训练的，可能也是这个原因

**Comment by sky-fly97** [comment]
> 1. 我也尝试了这个代码，不管是加载预训练参数darknet还是直接训练，都会出现recall=0,precision=0, 而且验证集上精度很低的问题。
> 2. 我也尝试了 eriklindernoren/PyTorch-YOLOv3 也一样有这个问题。
>    想水个比赛好难呀

我觉得我们的问题可能都是用了backbone来训练

**Comment by huangshenneng** [comment]
你好，看了你的源码，发现你的标签好像设置错了，数据预处理那里应该需要把标签+1的。

**Comment by edwardning** [comment]
> 把标签+1

可否指出具体位置？
时间太久我记不清了，不过印象中源码的训练精度是好的，如果标签出问题，精度应该天壤之别才对。
