### ISSUE TITLE
数据集保存位置

### ISSUE THREAD

**Issue by wk112503** [edwardning/PyTorch-YOLOv3-ModelArts#11]
你好，请问数据集是保存在哪里的啊，我使用这个模型训练的时候出现这个问题 File "code/train.py", line 55, in prepare_data_on_modelarts
    raise Exception('unzip trainval.zip Failed')
Exception: unzip trainval.zip Failed

**Comment by edwardning** [comment]
数据集是本地打包好，上传到OBS里边去的。
在my_utils/prepare_datasets.py里边有说明数据打包格式。

**Comment by edwardning** [comment]
> 你好，请问数据集是保存在哪里的啊，我使用这个模型训练的时候出现这个问题 File "code/train.py", line 55, in prepare_data_on_modelarts
> raise Exception('unzip trainval.zip Failed')
> Exception: unzip trainval.zip Failed

数据集是本地打包好，上传到OBS里边去的。
在my_utils/prepare_datasets.py里边有说明数据打包格式。

**Comment by wk112503** [comment]
Namespace(batch_size=32, checkpoint_interval=1, compute_map=False, data_config='config/custom.data', data_local='', data_url='trainval.zip', evaluation_interval=1, freeze_body_1=2, freeze_body_2=0, gradient_accumulations=2, img_size=416, init_method='', local_data_root='/cache/', lr_1=0.001, lr_2=1e-05, max_epochs_1=5, max_epochs_2=5, model_def='config/yolov3-custom.cfg', multiscale_training=True, n_cpu=8, pretrained_weights=None, train_local='', train_url='logs')

 File "/home/ma-user/work/my_utils/augmentations.py", line 8, in horisontal_flip
    targets[:, 2] = 1 - targets[:, 2]
TypeError: 'NoneType' object is not subscriptable
请问一下这个问题怎么解决阿

**Comment by edwardning** [comment]
> Namespace(batch_size=32, checkpoint_interval=1, compute_map=False, data_config='config/custom.data', data_local='', data_url='trainval.zip', evaluation_interval=1, freeze_body_1=2, freeze_body_2=0, gradient_accumulations=2, img_size=416, init_method='', local_data_root='/cache/', lr_1=0.001, lr_2=1e-05, max_epochs_1=5, max_epochs_2=5, model_def='config/yolov3-custom.cfg', multiscale_training=True, n_cpu=8, pretrained_weights=None, train_local='', train_url='logs')
> 
> File "/home/ma-user/work/my_utils/augmentations.py", line 8, in horisontal_flip
> targets[:, 2] = 1 - targets[:, 2]
> TypeError: 'NoneType' object is not subscriptable
> 请问一下这个问题怎么解决阿

你在modelarts上创建作业的时候，传入的参数不对啊。比如data_url我记得是全路径，而不是只'trainval.zip'。建议你先熟悉一下modelarts基本操作。
