### ISSUE TITLE
模型训练和提交测试问题

### ISSUE THREAD

**Issue by ZiQiangXie** [edwardning/PyTorch-YOLOv3-ModelArts#2]
请问一下，这个比赛模型可以在本地进行训练吗？然后上传自己的模型提交测试？
翻了几遍比赛介绍，没有找到详细的说明或者流程这些！

**Comment by edwardning** [comment]
1. 模型既可以在modelarts云端训练，也可以在本地训练。 判分的话，按要求提交模型测试就好了。
2. 这个项目是针对云上训练的，本地的话可以参考原作者项目：https://github.com/eriklindernoren/PyTorch-YOLOv3
3. 官方baseline里有一个指导文档，具体流程写的蛮清楚的，你可以参考下。

**Comment by ZiQiangXie** [comment]
多谢指导，多谢！！
