### ISSUE TITLE
改进

### ISSUE THREAD

**Issue by sky-fly97** [edwardning/PyTorch-YOLOv3-ModelArts#3]
大佬你好，请问可以推荐一些常用的改进tricks嘛，第一次参加这种比赛，还是小白....我看到模型当中已经有了数据增强的部分，请问还有哪些比较常用的提分方法呢？

**Comment by sky-fly97** [comment]
最后还有一个问题就是，默认score是0.3的，按理说降低self.score分数应该会变化的呀，但是我改到0.1/0.01分数变化都在小数点后两位，改到0.0001分数直接拉到0.02，发现是因为出现了负值坐标，仅仅改了self.score怎么会出现负值框呀

**Comment by sky-fly97** [comment]
![image](https://user-images.githubusercontent.com/55578436/82720325-2a56d900-9ce5-11ea-8581-0c53dd49092a.png)

**Comment by sky-fly97** [comment]
![image](https://user-images.githubusercontent.com/55578436/82720328-3a6eb880-9ce5-11ea-8e21-55c230c37339.png)

**Comment by sky-fly97** [comment]
score为0.01以上时不会出现负值框，设置为0.0001才会出现，然后分数就非常低了，大佬这是为什么呢？

**Comment by sky-fly97** [comment]
好吧，好像默认score也会出现负值的预测坐标....

**Comment by edwardning** [comment]
> 大佬你好，请问可以推荐一些常用的改进tricks嘛，第一次参加这种比赛，还是小白....我看到模型当中已经有了数据增强的部分，请问还有哪些比较常用的提分方法呢？

我不是大佬，也是第一次参加。。。 baseline里边的数据增强很简单的，多试几种效果会更好。

**Comment by edwardning** [comment]
> 最后还有一个问题就是，默认score是0.3的，按理说降低self.score分数应该会变化的呀，但是我改到0.1/0.01分数变化都在小数点后两位，改到0.0001分数直接拉到0.02，发现是因为出现了负值坐标，仅仅改了self.score怎么会出现负值框呀

这个应该和模型有关系吧

**Comment by sky-fly97** [comment]
> > 最后还有一个问题就是，默认score是0.3的，按理说降低self.score分数应该会变化的呀，但是我改到0.1/0.01分数变化都在小数点后两位，改到0.0001分数直接拉到0.02，发现是因为出现了负值坐标，仅仅改了self.score怎么会出现负值框呀
> 
> 这个应该和模型有关系吧

感谢~  那预测中出现负值还是因为模型的精度不够嘛，从来没遇到过还能预测到出现负值框...

**Comment by edwardning** [comment]
> > > 最后还有一个问题就是，默认score是0.3的，按理说降低self.score分数应该会变化的呀，但是我改到0.1/0.01分数变化都在小数点后两位，改到0.0001分数直接拉到0.02，发现是因为出现了负值坐标，仅仅改了self.score怎么会出现负值框呀
> > 
> > 
> > 这个应该和模型有关系吧
> 
> 感谢~ 那预测中出现负值还是因为模型的精度不够嘛，从来没遇到过还能预测到出现负值框...

你在本地试试？ 我感觉他那个在线部署的输出是由很多问题的

**Comment by sky-fly97** [comment]
好的，非常感谢您的帮助！------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Ning&amp;nbsp;Li&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月23日(星期六) 中午12:23
收件人:&nbsp;&quot;edwardning/PyTorch-YOLOv3-ModelArts&quot;<PyTorch-YOLOv3-ModelArts@noreply.github.com&gt;;
抄送:&nbsp;&quot;sky-fly97&quot;<595936905@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [edwardning/PyTorch-YOLOv3-ModelArts] 改进 (#3)
