### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by Donaghys** [edwardning/PyTorch-YOLOv3-ModelArts#4]
感谢大佬提供的代码，有两个问题希望大佬解答下
（1） config 下的train.txt 和val.txt 下自己的桶的地址怎么改成自己的呢？
（2）下载了 yolo的预训练模型 
这个指令 --pretrained_weights = s3://your_bucket/{model}  怎么添加呢？s3://是什么意思？
新手小白第一次用不明白，希望大佬赐教

**Comment by edwardning** [comment]
> n.txt 和val.txt 下自

1. 代码里默认的地址，如果你对model arts不是很熟悉的话，这个最好不要动。
2. 参考下官方baseline里边的指导文档，s3表示的是OBS桶的地址。

建议你先参照官方指导文档，把官方baseline跑一遍熟悉下流程，再去用其他版本或者其他模型。

**Comment by Donaghys** [comment]
感谢，已明了。
