### ISSUE TITLE
图像格式问题

### ISSUE THREAD

**Issue by CarryHJR** [edwardning/PyTorch-YOLOv3-ModelArts#5]
我看官方keras的那个inference函数里面没有涉及rgb和bgr的转换，大佬您的代码里也没有相关的转化，可我想官方keras的输入应该是按bgr的，pytorch的是按rgb的，两者在inference时应该有区别才对，很迷，希望大佬解答一下

**Comment by edwardning** [comment]
> 我看官方keras的那个inference函数里面没有涉及rgb和bgr的转换，大佬您的代码里也没有相关的转化，可我想官方keras的输入应该是按bgr的，pytorch的是按rgb的，两者在inference时应该有区别才对，很迷，希望大佬解答一下

我认为不管是RGB还是BGR，只需保证训练和推理保持一致即可。比如我训练和推理都是Image.open()打开图片，所以无所谓转换问题。

**Comment by CarryHJR** [comment]
可以的，got it
