### ISSUE TITLE
关于提交训练作业

### ISSUE THREAD

**Issue by YongshuaiZ** [edwardning/PyTorch-YOLOv3-ModelArts#6]
你好，请问为什么训练作业的会报这样的错误
<img width="402" alt="1" src="https://user-images.githubusercontent.com/53656644/83408724-b388b100-a445-11ea-9324-5e1971a3c630.PNG">

**Comment by edwardning** [comment]
> 你好，请问为什么训练作业的会报这样的错误
> <img alt="1" width="402" src="https://user-images.githubusercontent.com/53656644/83408724-b388b100-a445-11ea-9324-5e1971a3c630.PNG">

原因有很多种，建议你仔细看下日志出错的地方哈。
最有可能的原因：对比prepare_data_onmodelarts脚本里边的说明，检查下自己的压缩包目录是否合理。

**Comment by YongshuaiZ** [comment]
谢谢作者，问题已解决，是压缩时文件出了错



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ning Li"<notifications@github.com&gt;; 
发送时间: 2020年6月1日(星期一) 晚上9:08
收件人: "edwardning/PyTorch-YOLOv3-ModelArts"<PyTorch-YOLOv3-ModelArts@noreply.github.com&gt;; 
抄送: "七号门房"<2397627550@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [edwardning/PyTorch-YOLOv3-ModelArts] 关于提交训练作业 (#6)





  
你好，请问为什么训练作业的会报这样的错误
 
  
原因有很多种，建议你仔细看下日志出错的地方哈。
 最有可能的原因：对比prepare_data_onmodelarts脚本里边的说明，检查下自己的压缩包目录是否合理。
