### ISSUE TITLE
关于训练作业

### ISSUE THREAD

**Issue by Feng-Shilong** [edwardning/PyTorch-YOLOv3-ModelArts#7]
大佬你好，我在创建训练作业时AI引擎选择了pytorch，但是在运行中报错，日志中提示
from utils.logger import *
File "/cache/user-job-dir/PyTorch-YOLOv3-master/utils/logger.py", line 1, in <module>
import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
请问该怎么解决？

**Comment by edwardning** [comment]
> 大佬你好，我在创建训练作业时AI引擎选择了pytorch，但是在运行中报错，日志中提示
> from utils.logger import *
> File "/cache/user-job-dir/PyTorch-YOLOv3-master/utils/logger.py", line 1, in
> import tensorflow as tf
> ModuleNotFoundError: No module named 'tensorflow'
> 请问该怎么解决？

这是你自己写的代码吧？
tensorflow作为一个包导入就行了，推理的话在config.json里加上tensorflow及版本号，训练的话在pip_requirement里加上。

**Comment by Feng-Shilong** [comment]
不是我写的，是用的你发布的代码训练的，我这个问题解决了还有一些错误，方便留个QQ吗？

**Comment by edwardning** [comment]
> 不是我写的，是用的你发布的代码训练的，我这个问题解决了还有一些错误，方便留个QQ吗？

微信 18392888101
