### ISSUE TITLE
关于配置自己的预训练权重

### ISSUE THREAD

**Issue by YongshuaiZ** [edwardning/PyTorch-YOLOv3-ModelArts#8]

**Comment by edwardning** [comment]
pretrained_weights的地址那儿，把花括号去掉
| |
李宁
|
|
edwardning@163.com
|
签名由网易邮箱大师定制
在2020年6月2日 19:11，mark-zy<notifications@github.com> 写道：

你好，我想问一下，我按照要求配置了预训练权重，也将yolov3.weights上传到obs,为啥还会报错呀
