### ISSUE TITLE
关于划分训练集和测试集的问题

### ISSUE THREAD

**Issue by naomiLu** [edwardning/PyTorch-YOLOv3-ModelArts#9]
我看了一下prepare_datasets.py并没有划分训练测试集的代码，请问博主是根据什么划分的呢？谢谢你~

**Comment by edwardning** [comment]
> 我看了一下prepare_datasets.py并没有划分训练测试集的代码，请问博主是根据什么划分的呢？谢谢你~

图片地址分别放在了train.txt和val.txt里边，默认按8：2分的。
